### ISSUE TITLE
Instances cloneable?

### ISSUE THREAD

**Issue by timowevel1** [switnet-ltd/quick-jibri-installer#60]
Hey,

again I need your advice. Is it possible to clone the Videobridge/Jibri instances? So when I setup a videobridge using the script, is it possible to clone this server to attach another one?

Thank you.
Timo

**Comment by Ark74** [comment]
Well not really.
Every additional node is configured to connect to a specific JMS.
You will need to change the connection details manually and the instance ID, for each one, or just run the script and let it do what it does.

Also since you need an unique ID even if  for speed sake you clone the instance, you might want to check if the /etc/machine-id gets cloned too, that will remove the ability to use that as the jibri/jvb instance id.

**Comment by timowevel1** [comment]
Just had to change the muc-nickname each, works perfect

**Comment by Ark74** [comment]
Oh, then it was not to connect to another (JMS) server, but the same server.

Yes this will be the case, for the same JMS only change the nickname, that is done when running the the add-jibri-script.sh

Soon improved to be simple on scaling.
Glad to know it worked for you.

**Comment by timowevel1** [comment]
Yes, I just cloned the whole instance and let a script change the nickname.

**Comment by Ark74** [comment]
On the last update, we removed the incremental naming in favor of machine id.

So it's simpler to use the same script, when we first wrote it made sense to do it incremental, now days we believe it has no real use and complicate things beyond use, I think this will help to implement autoscalling.

**Comment by timowevel1** [comment]
I see your effort, thanks. But not suitable for aws. When the script is ran, you have to confirm the connection to the server with SSH, so it cannot run automatically. So I will continue with the script I made, setting the muc-nickname to a random string on machine bootup.

Thank you!
