### ISSUE TITLE
Getting NoMediaTimeout

### ISSUE THREAD

**Issue by timowevel1** [switnet-ltd/quick-jibri-installer#69]
Hey,
since your recent update I get a NoMediaTimeout, no matter which server I use.

 Transitioning from state Running to Error: NoMediaReceived SESSION No media received

Maybe you got an idea.

**Comment by Ark74** [comment]
Well there was an issue where the input was running behind the monitor.
So it always seemed the stream was empty, that was fixed some time ago.

I've noticed that this remained on single user on the room, you need to have at least 2 sources so it doesn't trigger
https://github.com/switnet-ltd/quick-jibri-installer/blob/master/quick_jibri_installer.sh#L913

I guess this behavior is an upstream issue, since AFAIC the values we added on the jibri.conf are the default values, we added so they can be tuned.
You might want to comment that line and see any change.

**Comment by timowevel1** [comment]
I just have set it to 300 minutes, works so far. Thanks.

**Comment by Ark74** [comment]
Be careful, I think that is best to try with the default value (comment the 30 seconds) because this is the timeout time you are setting.

I don't think you want the jibri to be waiting 5 hours before it times out.

If a jibri recording fails for who knows what, you want it to "free itself" and become available in a matter of second instead of 5 hours.

Not sure if recognizing a single stream (1 participant) as null is a bug or a feature.
We might want to open an issue upstream.

**Comment by timowevel1** [comment]
Ah, okay, then I will leave it on 30. Sure, normally there should be at least 2 people in a room.

Thank you.

**Comment by Ark74** [comment]
I would comment that value to see if that changes the behavior.
And maybe open an issue upstream, seems more a bug than a feature.

There might be cases where you might want to record yourself alone.
