### ISSUE TITLE
Jibri only recording audio to FLAC file. Can video be recorded too?

### ISSUE THREAD

**Issue by brimur** [switnet-ltd/quick-jibri-installer#7]
Hi, I know this is not your issue really but I was hoping you might know if recording a meeting properly is possible? I just ran your script on a clean Ubuntu install and everything is working great so thanks for that except recording is only audio. By properly I mean any webcams, desktop sharing etc, basically the contents of whole browser tab recorded to an mp4/mkv/ts file?

Thanks,
B

**Comment by Ark74** [comment]
Ohh, sorry maybe some clarification on that might help.

By default I have set cameras off, so you can turn it on when you want it.
Also only the moderator sign in with mic open, all the rest will join muted, so they don't disturb the meeting, mainly if hey arrive late.

They can turn on their mic just as the webcam.

Now, the FLAC recording is not what you want, you want *jibri* to make a proper recorder.
I'll be removing localrecording in future configurations since it's not very used and confuses people.

Please see the picture below,

![jibri](https://user-images.githubusercontent.com/7444518/90163130-4d7cac00-dd5b-11ea-823e-6e2fbafd69d6.png)

Let me know if that helps

**Comment by naveenbabusa** [comment]
One issue is in Aws the bash is not working it fails in kernel issue and mod loop asna fails . I tried in gcp it got installed not sure it had few challenges as it kept restarting the meeting once you start the recording and also when we did streaming . Also video was not getting streamed . Any guidance it seem to be unstable . Also grapans I was not able to access

**Comment by Ark74** [comment]
Please avoid hijack a thread, open one for that issue.

**Comment by Ark74** [comment]
Closing for now, as local recording is not enabled on the latest commits, let me know if jibri is what you were expecting.

**Comment by brimur** [comment]
Yep, Jibri was what I was looking for and it is working as expected. Thanks for the help!
