### ISSUE TITLE
Add oder remove user

### ISSUE THREAD

**Issue by tomcatcw1980** [switnet-ltd/quick-jibri-installer#92]
Hi there,

first of all: This is an amazing work. Many thanks for that. I tried out other installing tutorials with jibri and nothing worked in the end. This script works from the beginning!

Know I have only a question not realy an issue: Where can I add or remove users? I tried adding a new user with the following snippet

`sudo prosodyctl register alice video.mydomain.com secretpassword123`

But I receive an error:

`**************************
Prosody was unable to find lua-unbound
This package can be obtained in the following ways:

  Debian/Ubuntu | sudo apt install lua-unbound
       luarocks | luarocks install luaunbound
         Source | https://www.zash.se/luaunbound.html

Old DNS resolver library will be used
More help can be found on our website, at https://prosody.im/doc/depends
**************************`

Can you guys steer me in the right direction?

Thank you in advance
Christian

**Comment by Ark74** [comment]
That's not an error, maybe a warning at best. Since prosody 12, it ask for several packages for the prosody framework, but they are not required on Jitsi Meet, so yeah you get the message on any prosody change you make, still not necessary to our setup.

Have you tried login with the user you just created?

**Comment by Ark74** [comment]
Feel free to reopen if you think is necessary.
Regards
